#!/usr/bin/env bash
set -euo pipefail

# Codex defines subagents as TOML files in $CODEX_HOME/agents and cannot load
# them from a plugin, so the Markdown files in agents/ stay the single source of
# truth and this script projects them into the format Codex expects. Rerun it
# after adding or editing an agent.
#
# Usage: gen-codex-agents.sh [output-dir]   (default: ~/.codex/agents)

log() { printf '[gen-codex-agents] %s\n' "$*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_DIR="$SCRIPT_DIR/../agents"
OUT_DIR="${1:-$HOME/.codex/agents}"

# 1. Check what the conversion needs.
if ! command -v python3 >/dev/null 2>&1; then
  log "ERROR: python3 not on PATH; cannot generate agent definitions."
  exit 1
fi

if [ ! -d "$AGENTS_DIR" ]; then
  log "ERROR: agent directory not found: $AGENTS_DIR"
  exit 1
fi

# 2. Convert every Markdown agent into the TOML fields Codex requires.
mkdir -p "$OUT_DIR"

python3 - "$AGENTS_DIR" "$OUT_DIR" <<'PY'
import pathlib
import sys

agents_dir, out_dir = sys.argv[1], sys.argv[2]


def log(message):
    print(f"[gen-codex-agents] {message}", file=sys.stderr)


def unquote(value):
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        return value[1:-1].replace(value[0] * 2, value[0])
    return value


def parse(path):
    text = path.read_text()
    if not text.startswith("---\n"):
        return None, None
    end = text.find("\n---\n", 3)
    if end == -1:
        return None, None
    meta = {}
    for line in text[4:end].splitlines():
        if ": " in line:
            key, value = line.split(": ", 1)
            meta[key.strip()] = unquote(value.strip())
    return meta, text[end + 5 :].strip()


def toml_string(value):
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if "\n" in escaped:
        return '"""\n' + escaped + '\n"""'
    return '"' + escaped.replace('"', '\\"') + '"'


MARKER = "# Generated by scripts/gen-codex-agents.sh. Do not edit by hand."

written = set()
for path in sorted(pathlib.Path(agents_dir).glob("*.md")):
    meta, body = parse(path)
    if not meta or not meta.get("name") or not meta.get("description") or not body:
        log(f"ERROR: {path.name} has no name, description, or body.")
        sys.exit(1)

    lines = [
        "# Generated by scripts/gen-codex-agents.sh. Do not edit by hand.",
        f"# Source: agents/{path.name}",
        "",
        f"name = {toml_string(meta['name'])}",
        f"description = {toml_string(meta['description'])}",
    ]

    if meta.get("readonly", "").lower() == "true":
        lines.append('sandbox_mode = "read-only"')

    lines.append(f"developer_instructions = {toml_string(body)}")

    (pathlib.Path(out_dir) / f"{meta['name']}.toml").write_text("\n".join(lines) + "\n")
    written.add(meta["name"])

# Drop definitions this script generated for agents that no longer exist. The
# marker keeps it from touching agents the user wrote themselves.
removed = 0
for path in sorted(pathlib.Path(out_dir).glob("*.toml")):
    if path.stem in written:
        continue
    if path.read_text().startswith(MARKER):
        path.unlink()
        removed += 1

summary = f"wrote {len(written)} agent definitions to {out_dir}"
if removed:
    summary += f", removed {removed} for deleted agents"
log(summary)
PY
