#!/usr/bin/env bash
set -euo pipefail

# Codex turns a plugin's commands into skills on install, but skips any that use
# $ARGUMENTS, use Claude Code inline shell expansion, or are over roughly 3.8 KB.
# Custom prompts in $CODEX_HOME/prompts, the other way to publish a command, stopped
# loading in codex-cli 0.117.0, so the skipped commands would not reach Codex at all.
# This projects them into skills the same way Codex does, so the Markdown files in
# commands/ stay the single source of truth. Rerun it after adding or editing one.
#
# Usage: gen-codex-command-skills.sh [output-dir] [migrated-skills-dir]
#   output-dir          defaults to $CODEX_HOME/skills (or ~/.codex/skills)
#   migrated-skills-dir commands Codex already took, so they are not published twice

log() { printf '[gen-codex-command-skills] %s\n' "$*" >&2; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMANDS_DIR="$SCRIPT_DIR/../commands"
OUT_DIR="${1:-${CODEX_HOME:-$HOME/.codex}/skills}"
MIGRATED_DIR="${2:-}"

# 1. Check what the conversion needs.
if ! command -v python3 >/dev/null 2>&1; then
  log "ERROR: python3 not on PATH; cannot generate command skills."
  exit 1
fi

if [ ! -d "$COMMANDS_DIR" ]; then
  log "ERROR: command directory not found: $COMMANDS_DIR"
  exit 1
fi

# 2. Convert every command Codex did not take into a skill.
mkdir -p "$OUT_DIR"

python3 - "$COMMANDS_DIR" "$OUT_DIR" "$MIGRATED_DIR" <<'PY'
import pathlib
import sys

commands_dir, out_dir, migrated_dir = sys.argv[1], sys.argv[2], sys.argv[3]

PREFIX = "albino-command-"
MARKER = "<!-- Generated by scripts/gen-codex-command-skills.sh. Do not edit by hand. -->"
# Skills take no arguments, so the subject has to come from the conversation.
ARGUMENTS = "the subject the user gave in their message"


def log(message):
    print(f"[gen-codex-command-skills] {message}", file=sys.stderr)


def unquote(value):
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        return value[1:-1].replace(value[0] * 2, value[0])
    return value


def parse(path):
    text = path.read_text()
    if not text.startswith("---\n"):
        return None, None
    end = text.find("\n---\n", 3)
    if end == -1:
        return None, None
    meta = {}
    for line in text[4:end].splitlines():
        if ": " in line:
            key, value = line.split(": ", 1)
            meta[key.strip()] = unquote(value.strip())
    return meta, text[end + 5 :].strip()


def already_migrated(name):
    if not migrated_dir:
        return False
    return (pathlib.Path(migrated_dir) / f"source-command-{name}").is_dir()


written = set()
skipped = 0
for path in sorted(pathlib.Path(commands_dir).glob("*.md")):
    name = path.stem
    if already_migrated(name):
        skipped += 1
        continue

    meta, body = parse(path)
    if not meta or not meta.get("description") or not body:
        log(f"ERROR: {path.name} has no description or body.")
        sys.exit(1)

    body = body.replace("$ARGUMENTS", ARGUMENTS)
    skill_name = f"{PREFIX}{name}"
    hint = meta.get("argument-hint")
    intro = f"Use this skill when the user asks to run the `{name}` command"
    intro += f" ({hint})." if hint else "."

    document = "\n".join([
        "---",
        f"name: {skill_name}",
        f"description: {meta['description']}",
        "---",
        "",
        MARKER,
        f"<!-- Source: commands/{path.name} -->",
        "",
        f"# {skill_name}",
        "",
        intro,
        "",
        body,
        "",
    ])

    target = pathlib.Path(out_dir) / skill_name
    target.mkdir(parents=True, exist_ok=True)
    (target / "SKILL.md").write_text(document)
    written.add(skill_name)

# 3. Drop skills this script generated for commands that no longer exist, or that
#    Codex has since taken over. The marker keeps it away from other skills.
removed = 0
for target in sorted(pathlib.Path(out_dir).glob(f"{PREFIX}*")):
    skill_file = target / "SKILL.md"
    if target.name in written or not skill_file.is_file():
        continue
    if MARKER in skill_file.read_text():
        skill_file.unlink()
        for leftover in sorted(target.rglob("*"), reverse=True):
            leftover.rmdir() if leftover.is_dir() else leftover.unlink()
        target.rmdir()
        removed += 1

summary = f"wrote {len(written)} command skills to {out_dir}"
if skipped:
    summary += f", {skipped} already installed by Codex"
if removed:
    summary += f", removed {removed} stale"
log(summary)
PY
